import {
	AlertTriangle,
	Archive,
	ArchiveRestore,
	ArrowDownLeft,
	ArrowUpRight,
	Banknote,
	BarChart3,
	Book,
	BookOpen,
	Briefcase,
	Bug,
	Building,
	Cake,
	Car,
	ChevronLeft,
	ChevronRight,
	Coffee,
	Copy,
	CornerDownRight,
	CreditCard,
	DollarSign,
	Droplet,
	Dumbbell,
	Eye,
	EyeOff,
	Figma,
	FileText,
	Flame,
	Fuel,
	Gamepad2,
	Gift,
	GraduationCap,
	HandCoins,
	Heart,
	Home,
	Hotel,
	Inbox,
	Key,
	Landmark,
	Laptop,
	type LucideIcon,
	Music,
	Package,
	Palette,
	Pencil,
	PiggyBank,
	Pill,
	Plane,
	Plus,
	Shield,
	ShoppingBag,
	ShoppingCart,
	Smartphone,
	SprayCan,
	Tag,
	Target,
	Train,
	Trash2,
	Plane as TravelIcon,
	TrendingDown,
	TrendingUp,
	Tv,
	User,
	Utensils,
	Wallet,
	Wifi,
	X,
	Zap,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
	utensils: Utensils,
	coffee: Coffee,
	"shopping-cart": ShoppingCart,
	home: Home,
	key: Key,
	building: Building,
	wifi: Wifi,
	smartphone: Smartphone,
	"file-text": FileText,
	"shopping-bag": ShoppingBag,
	zap: Zap,
	droplet: Droplet,
	flame: Flame,
	"spray-can": SprayCan,
	bug: Bug,
	banknote: Banknote,
	user: User,
	"trending-up": TrendingUp,
	briefcase: Briefcase,
	"hand-coins": HandCoins,
	landmark: Landmark,
	"bar-chart-2": BarChart3,
	"credit-card": CreditCard,
	wallet: Wallet,
	car: Car,
	train: Train,
	plane: Plane,
	fuel: Fuel,
	dumbbell: Dumbbell,
	pill: Pill,
	shield: Shield,
	tv: Tv,
	music: Music,
	package: Package,
	palette: Palette,
	laptop: Laptop,
	figma: Figma,
	book: Book,
	"book-open": BookOpen,
	tag: Tag,
	"dollar-sign": DollarSign,
	"arrow-up-right": ArrowUpRight,
	"arrow-down-left": ArrowDownLeft,
	"trending-down": TrendingDown,
	gift: Gift,
	heart: Heart,
	cake: Cake,
	"graduation-cap": GraduationCap,
	travel: TravelIcon,
	hotel: Hotel,
	gamepad2: Gamepad2,
	"chevron-left": ChevronLeft,
	"chevron-right": ChevronRight,
	"corner-down-right": CornerDownRight,
	archive: Archive,
	"archive-restore": ArchiveRestore,
	eye: Eye,
	"eye-off": EyeOff,
	plus: Plus,
	target: Target,
	"piggy-bank": PiggyBank,
	inbox: Inbox,
	pencil: Pencil,
	"trash-2": Trash2,
	x: X,
	"alert-triangle": AlertTriangle,
	copy: Copy,
};

interface CategoryIconProps {
	name: string;
	size?: number;
	className?: string;
	style?: React.CSSProperties;
}

export function CategoryIcon({
	name,
	size = 20,
	className,
	style,
}: CategoryIconProps) {
	const Icon = ICON_MAP[name] || Tag;
	return <Icon size={size} className={className} style={style} />;
}

export const CATEGORY_ICONS = Object.keys(ICON_MAP);
